file(GLOB GUI_PROTOCOL_LIBRARY_UNIT_TESTS_SRC 
    "src/*"
)

file(GLOB GUI_PROTOCOL_LIBRARY_UNIT_TESTS_INC 
    "inc/*"
)

set( _GUI_PROTOCOL_LIBRARY_UNIT_TESTS_SOURCEFILES
    ${GUI_PROTOCOL_LIBRARY_UNIT_TESTS_SRC}
    ${GUI_PROTOCOL_LIBRARY_UNIT_TESTS_INC}
    files.cmake
)

source_group( "" FILES ${GUI_PROTOCOL_LIBRARY_UNIT_TESTS_TOPLEVEL})
source_group( gui_protocol_library_unit_tests/src FILES ${GUI_PROTOCOL_LIBRARY_UNIT_TESTS_SRC})
source_group( gui_protocol_library_unit_tests/inc FILES ${GUI_PROTOCOL_LIBRARY_UNIT_TESTS_INC})